#!/usr/bin/env bash
# Generated by pivota-spec init-dev-server
# Catalog entry: agent (multi-match: compose + react-next)
# Generator version: init-dev-server@1
#
# Edits ABOVE the END PIVOTA PREAMBLE marker are reset on regen.
# Edits BELOW the marker are preserved on regen.
#
# Why these choices (decision-trace; do not delete):
#   - `set -euo pipefail` not just `-e` — RESEARCH.md Pitfall 4 (silent pipe failures).
#   - `sha256sum` for lockfile hashing — RESEARCH.md "Don't hand-roll" (universal
#     coreutils, no extra dep vs blake3 / git hash-object / md5sum).
#   - Backoff 1s / 2s / 4s — Claude's Discretion per CONTEXT.md (small base, predictable).
#   - Log destination `/tmp/pivota-dev.log` — Open Question #4 resolved (always
#     writable inside Daytona sandboxes; matches existing convention).
#   - Agent fallback: project matches both compose and react-next catalogs.
#     compose entry takes precedence (docker-compose.yml is the deployment unit);
#     EXEC_CMD runs `docker compose up` which builds and starts the full stack.
#   - docker-compose owns multi-process orchestration; single-process retry loop
#     in wrapper-template.sh applies (multi-process-template.md §6 fast path).

set -euo pipefail

# === Bash version guard (RESEARCH.md Pitfall 8) ===
if (( BASH_VERSINFO[0] < 4 )) || { (( BASH_VERSINFO[0] == 4 )) && (( BASH_VERSINFO[1] < 3 )); }; then
  echo "[pivota] bash 4.3+ required for 'wait -n'; found ${BASH_VERSION}" >&2
  exit 127
fi

# === D-11.4: tee stdout/stderr to /tmp/pivota-dev.log AND pass through ===
mkdir -p /tmp
exec > >(tee -a /tmp/pivota-dev.log) 2>&1
echo "[pivota] $(date -Iseconds) start-dev.sh begin (catalog: agent/compose+react-next)"

# === D-11.1 + D-11.2: per-stack 0.0.0.0 binding ===
# Compose services control their own bind addresses via the `ports:` block in
# the compose file. The app service already binds 0.0.0.0:3000:3000. No env
# var is needed here — compose entry ENV_PREAMBLE is intentionally empty.

# === D-11.3: .env.example -> .env transitional copy (until Phase 38) ===
if [[ ! -f .env && -f .env.example ]]; then
  echo "[pivota] copying .env.example -> .env (Phase 38 will replace this hack)"
  cp .env.example .env
fi

# === D-12: no lockfile for compose (docker images cached by Docker layer model) ===
SENTINEL="/tmp/pivota-setup-sentinel"
LOCK_FILE_PATH=""
INSTALL_PRESENCE_CHECK=""
INSTALL_CMD=""

# (install section intentionally empty for compose — docker compose up handles it)

# === D-14: retry loop (3 attempts, exponential backoff 1s / 2s / 4s) ===
EXEC_CMD='docker compose up'
ATTEMPT=1
DELAY=1
while (( ATTEMPT <= 3 )); do
  echo "[pivota] attempt $ATTEMPT: $EXEC_CMD"
  if bash -c "$EXEC_CMD"; then
    echo "[pivota] inner command exited 0; propagating success"
    exit 0
  fi
  EXIT_CODE=$?
  if (( ATTEMPT == 3 )); then
    echo "[pivota] all 3 attempts failed (last exit=$EXIT_CODE); surfacing failure"
    exit "$EXIT_CODE"
  fi
  echo "[pivota] attempt $ATTEMPT failed (exit=$EXIT_CODE); retrying in ${DELAY}s"
  sleep "$DELAY"
  DELAY=$(( DELAY * 2 ))
  ATTEMPT=$(( ATTEMPT + 1 ))
done

# Unreachable, but keep for analyzer happiness
exit 1
# === END PIVOTA PREAMBLE ===
# Below this marker, projects may add custom shutdown / setup logic.
# This region is PRESERVED across regenerations.
